kind: Deployment
apiVersion: apps/v1
metadata:
  name: ch-sso
  namespace: ch
  labels:
    app: ch-sso
  annotations:
    deployment.kubernetes.io/revision: '1'
    kubesphere.io/creator: zhimin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ch-sso
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ch-sso
    spec:
      containers:
        - name: container-8lalcy
          image: 'registry.kubeoperator.io:8082/ch/ch-sso:${DATETIME}'
          ports:
            - name: tcp-8080
              containerPort: 8080
              protocol: TCP
          env:
            - name: JAVA_OPTS
              value: >-
                -Dnacos.config.server-addr=nacos.public.svc.cluster.local:8848
                -Dnacos.config.namespace=ff29ab57-4f4c-4c7a-8c96-d8ad70459d50
      imagePullSecrets:
        - name: ch-nexus