server:
  port: 7000

logging:
#  config: classpath:conf/logback-test.xml
  level:
    com.ch: debug
    com.alibaba.nacos.client: warn
  file:
    path: logs
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
jwt:
  #jwt的加密字符串
  secret: eyJleHAiOjE1NDMyMDUyODUsInN1YiI6ImFkbWluIiwiY3Jl
  #jwt token有效时间（分钟）
  tokenExpired: 30m
  refreshTokenExpired: 1d
captcha:
  ##支持项目路径,以classpath:开头,取resource目录下路径,例：classpath:images/jigsaw
  jigsaw: classpath:static/images/jigsaw
  ##支持项目路径,以classpath:开头,取resource目录下路径,例：classpath:images/pic-click
  pic-click: classpath:static/images/pic-click
  type: DEFAULT
  # local caffeine redis
  cache-type: redis
  #右下角水印文字
  water-mark:
  #右下角水印字体(宋体)
  water-font: \u5b8b\u4f53
  #点选文字验证码的文字字体(宋体)
  font-type: \u5b8b\u4f53
  #校验滑动拼图允许误差偏移量(默认5像素)
  slip-offset: 5
  #aes加密坐标开启或者禁用(true|false)
  aes-status: true
  #滑动干扰项(0/1/2)
  interference-options: 2

spring:
  thymeleaf:
    cache: false
  redis:
    ##
    jedis:
      pool:
        ### 连接池最大连接数（使用负值表示没有限制）
        max-active: 9
        ### 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        ### 连接池中的最大空闲连接
        max-idle: 9
        ### 连接池中的最小空闲连接
        min-idle: 0
    ### 连接超时时间（毫秒）
    timeout: 60000
    ### Redis数据库索引(默认为0)
    host: 192.168.0.203
    port: 6379
    password: admin123
    database: 1
