DROP TABLE IF EXISTS `PERSISTENT_TOKEN`;
CREATE TABLE `PERSISTENT_TOKEN` (
  `SERIAL` varchar(36) NOT NULL,
  `EXPIRES` datetime DEFAULT NULL,
  `TOKEN` varchar(100) DEFAULT NULL,
  `USERNAME` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`SERIAL`),
  UNIQUE KEY `UK_PERSISTENT_TOKEN_TOKEN` (`TOKEN`),
  UNIQUE KEY `UK_PERSISTENT_TOKEN_USERNAME` (`USERNAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '持久化TOKEN表';
